# Generated by Django 4.2.5 on 2023-09-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0012_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
