# Generated by Django 4.2.5 on 2023-09-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0013_rename_tools_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='task',
        ),
    ]
